MCU = STM32F401
BOOTLOADER = tinyuf2
CUSTOM_MATRIX = lite

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

LTO_ENABLE = yes

QUANTUM_LIB_SRC += analog.c
SRC += matrix.c ec_switch_matrix.c
